### ISSUE TITLE
Slight syntax difference breaks example.py on the Pico W

### ISSUE THREAD

**Issue by joewez** [hugokernel/micropython-nanoweb#18]
The example.py file does not run correctly on a Pico W because the `sys.implementation` function returns **_mpy** which does not match the current value being returned... **mpy**.  Not sure how this should be handled.

**Comment by hugokernel** [comment]
Not sure it is a Nanoweb related problem.

Could you send an example ?

**Comment by gramps2022** [comment]
As an absolute novice in this area I can't contribute any more than the fact that today I have also been trying to run the example on Pico W and I'm also seeing 'mpy' errors, e.g.:
Task exception wasn't retrieved
future: <Task> coro= <generator object 'handle' at 20025020>
Traceback (most recent call last):
  File "uasyncio/core.py", line 1, in run_until_complete
  File "nanoweb.py", line 153, in handle
  File "nanoweb.py", line 108, in generate_output
  File "<stdin>", line 66, in wrapper
  File "<stdin>", line 85, in api_status
AttributeError: 'tuple' object has no attribute 'mpy'

**Comment by chrisbie77** [comment]
The current implementation of MicroPython on the Pico W seems to  expect  _mpy  instead of  mpy  in the sys.* library, as per [the MicroPython docs](https://docs.micropython.org/en/latest/library/sys.html)

Change "sys.implementation.mpy" to "sys.implementation._mpy" on line 73 of example.py and it all works fine for me on the Pico W without exceptions, and displays and updates the system info as it should. 



![upython_rp2_nanoweb](https://user-images.githubusercontent.com/17858797/206211954-a0403b92-be94-412f-8247-16a066abd4c1.png)
